pass a project as an alternative to detection

diff --git a/bin/download-and-check b/bin/download-and-check
--- a/bin/download-and-check
+++ b/bin/download-and-check
@@ -3,12 +3,14 @@ HASH=""
 FILE=""
 URL=""
 TAG=""
-while getopts "f:u:h:t:" opt ; do
+PROJECT=""
+while getopts "f:u:h:t:p:" opt ; do
   case $opt in
     f) FILE="$OPTARG";;
     u) URL="$OPTARG";;
     h) HASH="$OPTARG";;
     t) TAG="$OPTARG";;
+    p) PROJECT="$OPTARG";;
     *)
       echo "unknown arg $opt"
       exit 1
@@ -36,9 +38,13 @@ CURHASH=$(sha256sum "$FILE" | cut -c 1-7)
 [ -n "$TAG" ] && TAG="'$TAG'"
 
 if [ -n "$PKGS_LIST" ]; then
-  if echo "$URL" | grep -q "https://github.com"; then
-    echo "$URL" | cut -d "/" -f 4,5 | sed 's/^/check_version "/g;s/$/"/g' | sed "s/$/ $TAG/g" >> "$PKGS_LIST"
+  if [ -z "$PROJECT" ]; then
+    if echo "$URL" | grep -q "https://github.com"; then
+      PROJECT="$(echo "$URL" | cut -d "/" -f 4,5)"
+    fi
   fi
+  [ -z "$PROJECT" ] && echo "unable to read project/unset?" && exit 1
+  echo "$PROJECT" | sed 's/^/check_version "/g;s/$/"/g' | sed "s/$/ $TAG/g" >> "$PKGS_LIST"
 fi
 
 exit 0
